version: '3.1'
services:
  jiang-admin:
    restart: always
    image: 35.241.113.30:5000/jiang-admin
    container_name: jiang-admin
    ports:
      - 8888:8888
    networks:
      - admin_network
networks:
  admin_network: